Conditional variable was replaced with channel notifier
networkservicemesh/cmd-exclude-prefixes-k8s pull request #18
Opened 2020-10-26 15:47 UTC by tigrulya-exe

Signed-off-by: Tigran Manasyan <tigran.manasyan@xored.com>

2020-10-27 06:55 UTC, denis-tingajkin requested changes

2020-10-27 06:55 UTC, denis-tingajkin commented on internal/utils/channel_notifier.go
> +func NewChannelNotifiable() Notifiable {
Let's just use the channel indirect

2020-10-27 12:11 UTC, tigrulya-exe commented on internal/utils/channel_notifier.go
> +func NewChannelNotifiable() Notifiable {
Replaced with channel

2020-10-27 13:51 UTC, denis-tingajkin approved these changes
Looks good to me 
@tigrulya-exe Do you plan to cover bug by the unit test to prevent regressions?

2020-10-27 13:56 UTC, tigrulya-exe commented
> @tigrulya-exe Do you plan to cover bug by the unit test to prevent regressions?
I think it'll be hard to reproduce such behaviour in unit test. But we have integration test with all sources, when the following situation might happen.

2020-10-27 17:54 UTC, denis-tingajkin commented
@tigrulya-exe Can we add some light test prefix sources? I think we should try to cover this issue by unit testing to minimize runs of integration tests.

2020-10-28 04:36 UTC, tigrulya-exe commented
@denis-tingajkin added unit test with all sources

2020-10-28 06:38 UTC, merged